services:
  cockroach:
    image: cockroachdb/cockroach:v25.2.4
    command: start-single-node --insecure --advertise-addr=localhost
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - crdb-data:/cockroach/cockroach-data

volumes:
  crdb-data:
